config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post "/google_login" => "users/sessions#google_create"
  end
  
  resources :users do
    member do
      get 'events'
      get 'hidden_events'
    end
    resources :unfriendships
  end 
  
  resources :events 

  resources :events do 
    member do
      get 'caltest'
      get 'report'
      patch 'report', action: 'update_report'
      post 'cancel'
    end
  end

  resources :comments do
    member do
      patch 'create'
      delete 'delete'
      patch 'update'
    end
  end

  resources :rsvps do
    member do
      patch 'update'
      get   'edit'
      patch 'update_email_comments_setting'
      get   'rsvp_reminder'
      get   'turn_off_comments'
      patch 'hide'
      patch 'unhide'
    end
  end

  namespace :admin do
    resources :events
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable,  :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :lockable, :validatable
 
  #Relationships
  has_many :events, foreign_key: "owner_id", class_name: "Event"
  has_many :rsvps
  has_many :unfriendships
  has_many :unfriends, through: :unfriendships

  #Validations
  validates_uniqueness_of :email

  #Scopes
  scope :confirmed, -> { where("confirmed = ?", true) }

  #people that you have invited in the past or that have invited you
  def my_people
    my_people = []

    my_events = Event.where(owner: self)
    my_events.each do |event|
      rsvps = event.rsvps
      rsvps.each do |rsvp|
        unless rsvp.user.nil? or rsvp.user.in? my_people or rsvp.user == self or rsvp.user.in? self.unfriends
          my_people << rsvp.user
        end
      end
    end

    my_rsvps = Rsvp.where(user: self)
    my_rsvps.each do |rsvp|
      unless rsvp.user.nil? or rsvp.event.owner.in? my_people or rsvp.user == self or rsvp.user.in? self.unfriends
        my_people << rsvp.event.owner
      end
    end

    my_people.sort_by{|p| p[:email]}

  end
   
  def flake_factor 
    reports = self.rsvps.reported
    flakes = reports.flaked

    unless reports.count == 0
      return flakes.count.to_f/reports.count.to_f
    else
      return nil
    end 
  end

  def reliability_factor
    flakiness = flake_factor
    if flakiness
      return 1.0 - flake_factor
    else
      return nil
    end
  end

  def is_invited_to? event
    self.in? event.invitees
  end 

  ######### Statistics Methods #######
  
  #Average number of confirmed RSVPs for events that this user plans
  def average_rsvp_yes_count
    rsvp_count = 0
    my_events = self.events.confirmed
    my_events.each do |event|
      rsvp_count += event.rsvps.said_yes.count 
    end

    rsvp_count.to_f/my_events.count.to_f
  end

  def percent_yes
    total_rsvps = self.rsvps.count
    said_yes = self.rsvps.said_yes.count
    return (said_yes.to_f/total_rsvps.to_f)*100
  end

  def percent_no
    total_rsvps = self.rsvps.count
    said_no = self.rsvps.said_no.count
    return (said_no.to_f/total_rsvps.to_f)*100
  end

  def percent_none
    return 100 - percent_no - percent_yes
  end

  # Watch out for n+1 queries here (and in sub-methods)
  # 
  # @note If you change this math, make sure you update the tests in
  # test/models/user_test also
  def sipping_points
    # An ActiveRecord::Relation to scope to only tipped events
    tipped_event_rsvps = rsvps.answered.joins(:event).merge(Event.tipped)

    # Points from this user's Events
    events.tipped.to_a.sum(&:sipping_points) +
    # Points from this user's RSVPs (earned by responding to invites)
    tipped_event_rsvps.to_a.sum(&:sipping_points) +
    # Points from this user's attendance reports (earned by attending events)
    tipped_event_rsvps.reported.to_a.sum(&:attendance_points)
  end

  ######### End Statistics Methods ###


  ########## String Generators #######

  def display_name
    if self.name.nil? or self.name.blank?
      return self.email
    else
      return self.name
    end
  end

  def to_s
    name || email
  end

  def reliability
    if self.reliability_factor
      return (reliability_factor * 100).round.to_s + "%"
    else
      return ""
    end
  end

  #Gmail doesn't like people with 1 name.  If a person has only
  #1 Name, set the from to the Sipping Point stead of the name
  def email_name
    if self.display_name.split(' ').count == 1
      return "Sipping Point"
    else
      return self.name
    end
  end

  ########## End String Generators #######


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    
    #Check Session for errors, email, and name
    @email_error = session[:email_error]
    @password_error = session[:password_error]
    @password_confirmation_error = session[:password_confirmation_error]
    @email = session[:email]
    @name = session[:name]
    session[:email_error] = nil
    session[:password_error] = nil
    session[:password_confirmation_error] = nil 
    session[:email] = nil
    session[:name] = nil

    build_resource({})
    set_minimum_password_length
    yield resource if block_given?
    respond_with self.resource
  end

  # POST /resource
  def create
    self.resource = User.find_by(email: sign_up_params[:email], confirmed: false)

    if resource.nil?
      self.resource = User.where(email: sign_up_params[:email]).new
    end
    
    resource.name = sign_up_params[:name]
    resource.password = sign_up_params[:password]
    resource.password_confirmation = sign_up_params[:password_confirmation]

    saved = resource.save

    if saved
      if resource.active_for_authentication?
        resource.confirmed = true
        resource.save
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length

      #Save old values and set errors
      resource.errors.each do |key,value|
        session[(key.to_s + "_error").to_sym] =  value
      end
      session[:email] =  sign_up_params[:email]
      session[:name] = sign_up_params[:name]
      
      redirect_to new_user_registration_path
    end
  
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update

    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    #Using Form_Tag instead of Form_For, Set Custom account_update_params
    account_update_params = custom_account_update_params params

    if account_update_params[:password_confirmation].blank? and account_update_params[:password].blank?
      account_update_params.delete(:current_password)
      resource_updated = resource.update_without_password(account_update_params)
    else
      resource_updated = update_resource(resource, account_update_params)
    end

    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :avatar_url
  # end

  # Sipping Point is using form_tag instead of form_for.  Form_tag allows for easier customization, but requires the 
  # default params to be overwritten since they are not associated with a model.
  def custom_account_update_params params
    custom_params  = {}
    [:email, :name, :avatar_url, :password, :password_confirmation, :current_password].each do |key|
      custom_params[key] = params[key]
    end
    return custom_params
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  #GET /resource/sign_in
  #def new
  #  super
  #end

  # POST /resource/sign_in
  def create
    super
    current_user.confirmed = true
    current_user.save 
  end

  def google_create
    #self.resource = warden.authenticate!(auth_options)
    current_user = google_verify params['id_token']
    
    if current_user 
      puts 'success so far'
      current_user.confirmed = true
      current_user.save 
      sign_in(:user, current_user)
      hash = {email: current_user.email}
      render json: hash
    end 
    #set_flash_message!(:notice, :signed_in)

  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def google_verify id_token

    user_hash = GoogleAuth.new.verify id_token

    unless user_hash[:result]
      return nil
    end

    user = User.find_or_create_by(email: user_hash[:email].downcase) do |u|
      u.password = u.password_confirmation = Devise.friendly_token.first(8)
    end

    if user.avatar_url.blank?
      user.avatar_url = user_hash[:picture]
      user.save
    end

    return user

  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :events, :hidden_events]
  before_action :authenticate_user!, except: [:show]
  before_action :confirm_user, except: [:index, :show]
  before_action :admin_only, only: [:index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def events

    @my_future_events = @user.rsvps.upcoming.not_hidden.sorted_by_earliest
    @my_prior_events = @user.rsvps.prior.not_hidden.sorted_by_latest
    @hidden_rsvps = @user.rsvps.hidden
    
    if @user == current_user 
      respond_to do |format|
        format.html { render :events }
      end
    else 
      redirect_to root_url
    end 

  end

  def hidden_events
    @rsvps = @user.rsvps.hidden
    
    if @user == current_user 
      respond_to do |format|
        format.html { render :hidden_events }
      end
    else 
      redirect_to root_url
    end 

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #Also need to update allowed params in the registratiosn_controller 
      params.require(:user).permit(:email, :name, :avatar_url)
    end

    def admin_only
      unless current_user.administrator
        redirect_to root_url
      end
    end

    def confirm_user
      unless current_user == @user or current_user.administrator
        redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_past_event_tile.html.haml
.panel-body
  %a{href: event_path(rsvp.event)}
    .panel-text
      .grid-cover-photo
        -unless rsvp.event.event_photo.url.nil?
          %img{src: rsvp.event.event_photo.url}
        -else
          %img{src: '/assets/sp_logo.png'}
        %span.overlay-text
          =rsvp.past_simple_status_string
      .sp-font.future-grid-title
        =rsvp.event.name
      .div.row.small-text
        %div.col-md-12
          %i.fa.fa-calendar.panel-text
          =rsvp.event.display_time
      
  %button.spacer.btn.panel-text.event_trash_button{ "data-id" => rsvp.hash_key }
    %i.fa.fa-trash.panel-text
    Delete Invitation  

app/views/users/_upcoming_event_tile.html.haml
.panel-body.translucent
  %a{href: event_path(rsvp.event)}
    .panel-text
      .grid-cover-photo
        -unless rsvp.event.event_photo.url.nil?
          %img{src: rsvp.event.event_photo.url}
        -else
          %img{src: '/assets/sp_logo.png'}
        %span.overlay-text
          =rsvp.simple_status_string
      .sp-font.future-grid-title.no-dec
        =rsvp.event.name
      .div.row.small-text
        %div.col-md-6
          %i.fa.fa-calendar.panel-text
          =rsvp.event.display_time
        %div.col-md-6
          =rsvp.event.yes_count_phrase
      
      -if rsvp.event.status == Event::CONFIRMED
        .progress.zero-margin-below
          .progress-bar.progress-bar-info.zero-margin-below{:role => "progressbar", :style => "width:" + rsvp.event.percent_complete.to_s + "%"}
            ="It's on!"
      -elsif rsvp.event.expired?
        .progress.zero-margin-below
          .progress-bar.progress-bar-danger.zero-margin-below{:role => "progressbar", :style => "width:" + rsvp.event.percent_complete.to_s + "%"}
            =rsvp.event.percent_complete.round.to_s + "%"
        %div.row.small-text
          ="Deadline to RSVP: " + rsvp.event.display_deadline
      -elsif rsvp.event.deleted?
        .progress.zero-margin-below
          ="Canceled by " + rsvp.event.owner.display_name 
      -else 
        .progress.zero-margin-below
          .progress-bar.progress-bar-danger.progress-bar-striped.active.zero-margin-below{:role => "progressbar", :style => "width:" + rsvp.event.percent_complete.to_s + "%"}
            =rsvp.event.percent_complete.round.to_s + "%"
        %div.row.small-text
          ="Deadline to RSVP: " + rsvp.event.display_deadline
  -if rsvp.event.expired? or rsvp.no? or rsvp.event.deleted?
    %button.spacer.btn.panel-text.event_trash_button{ "data-id" => rsvp.hash_key }
      %i.fa.fa-trash.panel-text
      Delete Invitation  

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/events.html.haml
%section.static-header
  %div.container
    -if @user.rsvps.count < 1
      %h1
        You have no events.  
    -else
      -@my_future_events.in_groups_of(3).each do |row|
        %div.row
          -row.each do |rsvp|
            %div.col-md-4
              -if rsvp
                -if rsvp.no? or rsvp.event.expired? or rsvp.event.deleted?
                  .panel.dim{id: rsvp.hash_key.to_s + '_block'}
                    = render :partial => "upcoming_event_tile", :locals => {rsvp: rsvp}   
                -else
                  .panel{id: rsvp.hash_key.to_s + '_block'}
                    = render :partial => "upcoming_event_tile", :locals => {rsvp: rsvp}   



      %h2.sp-font
        Past Events                 
      -@my_prior_events.in_groups_of(4).each do |row|
        %div.row
          -row.each do |rsvp|
            %div.col-md-3
              -if rsvp
                -if rsvp.no? or rsvp.event.expired? or rsvp.event.deleted?
                  .panel.dim{id: rsvp.hash_key.to_s + '_block'}
                    = render :partial => "past_event_tile", :locals => {rsvp: rsvp}   
                -else
                  .panel{id: rsvp.hash_key.to_s + '_block'}
                    = render :partial => "past_event_tile", :locals => {rsvp: rsvp}   



  %center
    %h4{:id => 'link_to_deleted_events', :style => "display:" + (@hidden_rsvps.count > 0 ? 'normal' : 'none' ) + ';'}
      = link_to 'My Deleted Events', hidden_events_user_url(@user), :class => 'white-link'
  

%div.fill-footer

:javascript
  // On click for a button
  $(".event_trash_button").click(function(){
    // Get the id data attribute
    var id = $(this).data("id");
    var block = document.getElementById(id + '_block');
    var delete_link = document.getElementById('link_to_deleted_events');
    delete_link.style.display = 'block';
    block.remove();
    $.ajax({
      type: 'PATCH',
      url: '#{root_url}' + 'rsvps/' + id + '/hide'
    });
  });

  

app/views/users/hidden_events.html.haml
%section.static-header
  %div.container
    -if @rsvps.count < 1
      %h1
        You have no hidden events.  
    -else
      %div{id: 'deleted-section'}
        %h2
          ="Deleted Events"
        .panel.translucent
          .panel-body
            .panel-text
              %table.table.table-center.table-striped{id: "deleted"}
                %thead
                  %tr
                    %th.text-center
                      Name
                    %th.text-center
                      Date
                    %th.text-center
                      Sipping Point
                    %th.text-center
                      Confirmed
                    %th.text-center
                      Status
                    %th.text-center
                      Un-Delete
                %tbody
                  -@rsvps.each do |rsvp|
                    %tr{ :id => rsvp.hash_key + '_row'}
                      %td
                        =link_to rsvp.event.name, event_path(rsvp.event)
                      %td
                        -if rsvp.event.time
                          =rsvp.event.display_time
                      %td
                        =rsvp.event.threshold
                      %td
                        =rsvp.event.rsvps.where(response: true).count
                      %td
                        =rsvp.event.short_description 
                      %td.panel-text.event_trash_button{ "data-id" => rsvp.hash_key }
                        %i.fa.fa-lg.fa-undo   

      %div{id: 'deleted-section-m'}
        %h2
          ="Past Events"
        .panel.translucent
          .panel-body
            .panel-text
              %table.table.table-center.table-striped{id: "past-events-m"}
                %tbody
                  -@rsvps.joins(:event).order('events.time ASC NULLS LAST').each do |rsvp|
                    %tr{ :id => rsvp.hash_key + '_row_m'}
                      %td
                        %div.row
                          %h4.col-xs-12.strong
                            =link_to rsvp.event.name, event_path(rsvp.event)
                        %div.row  
                          %div.col-xs-12
                            -if rsvp.event.time
                              =rsvp.event.display_time
                        %div.row
                          %div.col-xs-12
                            ="Status: " + rsvp.event.short_description 
                        %div.row
                          %div.col-xs-12
                            %div.panel-text.event_trash_button{ "data-id" => rsvp.hash_key }
                              %i.fa.fa-lg.fa-undo
                              Un-Delete                                  
  %center
    %h4
      = link_to 'Back to My Events', events_user_url(@user), :class => 'white-link'  

%div.fill-footer


:javascript
  // On click for a button
  $(".event_trash_button").click(function(){
       // Get the id data attribute
       var id = $(this).data("id");
       var row = document.getElementById(id + '_row');
       var rowm = document.getElementById(id + '_row_m')
       rowm.remove();
       row.remove();
       $.ajax({
        type: 'PATCH',
        url: '#{root_url}' + 'rsvps/' + id + '/unhide'
       });
  });

  //Handle Responsiveness
  function respond(){
    if (screen.width>=568) {
      $('#deleted-section').show();
      $('#deleted-section-m').hide();
    }
    else  {
      $('#deleted-section').hide();
      $('#deleted-section-m').show();
    }
  };

  window.onresize = function() {
    respond();
  };

  $(document).ready(function() {
    $('#deleted').dataTable({
      "bPaginate": false,"bInfo" : false,    
      'aoColumnDefs': [{'bSortable': false,'aTargets': [-1]}],
      "order": [[ 1, "desc" ]]
      });

    respond();
  } );

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%section.static-header
  %div.container
    %h1.static-header-title
      -unless @user.avatar_url.blank?
        %img.img-circle{src: @user.avatar_url, style: "height: 80px; width: 80px;"}
        %br
      =@user.display_name.strip
      %br
      %span.badge{title: "#{@user.display_name} has earned #{@user.sipping_points} Sipping Points.  Be the first to earn 1,000,000 Sipping Points to claim a free Spiderman Pez Dispenser. *Conditions subject to change without notice.", data: {:placement => "right"}}
        %i.fa.fa-2x.fa-trophy
          = @user.sipping_points
    %div.col-md-10.col-md-offset-1
      .panel.translucent
        .panel-body
          .panel-text
            -if @user.reliability_factor
              %div.row
                %h4
                  Reliability Rating: 
                  =@user.reliability
                -if @user.reliability_factor >= 0.80
                  %i.fa.fa-smile-o.fa-3x
                -elsif @user.reliability_factor >= 0.60
                  %i.fa.fa-meh-o.fa-3x
                -else
                  %i.fa.fa-frown-o.fa-3x
              %div.row
                %h4
                  =@user.display_name + " has flaked " + pluralize(@user.rsvps.flaked.count.to_s, "time") + "."
            -else
              %h4
                =@user.display_name + " does not have an attendance history yet."

      .panel.translucent
        .panel-body
          .panel-text
            -if @user.rsvps.count > 0
              %h4
                =@user.display_name + " has been invited to " + pluralize(@user.rsvps.count.to_s, "event") + "."
              %div.row{:style => "text-align: center;"}
                %div.col-md-4
                  ="Answered YES " + pluralize(@user.rsvps.said_yes.count, "Time")
                %div.col-md-4
                  ="Answered NO " + pluralize(@user.rsvps.said_no.count, "Time")
                %div.col-md-4
                  =pluralize(@user.rsvps.unanswered.count, "RSVP") + " unanswered"

              %div.row
                %div.col-md-1  
                %div.col-md-10  
                  .progress
                    .progress-bar.progress-bar-success{:style => "width: " + @user.percent_yes.to_s + "%"}
                      =@user.percent_yes.round(0).to_s + "% Yes"
                    .progress-bar.progress-bar-danger{:style => "width: " + @user.percent_no.to_s + "%"}
                      =@user.percent_no.round(0).to_s + "% No"
                    .progress-bar.progress-bar-warning{:style => "width: " + @user.percent_none.to_s + "%"}
                      =@user.percent_none.round(0).to_s + "% Ignored"
            -else
              %h4
                =@user.display_name + " has not been invited to any events yet."

      .panel.translucent
        .panel-body
          .panel-text
            -if @user.events.confirmed.count > 0
              %div.row
                %h4
                  =@user.display_name.to_s + " has planned " + pluralize(@user.events.confirmed.count, "successful event") + "."
              %div.row
                %h4
                  ="On average, " + @user.average_rsvp_yes_count.round(1).to_s + " people respond YES to these events."
            -else
              %h4
                =@user.display_name + " has not planned any events yet."

:javascript
  $(function () {
    $(".badge").tooltip()
  })