config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post "/google_login" => "users/sessions#google_create"
  end
  
  resources :users do
    member do
      get 'events'
      get 'hidden_events'
    end
    resources :unfriendships
  end 
  
  resources :events 

  resources :events do 
    member do
      get 'caltest'
      get 'report'
      patch 'report', action: 'update_report'
      post 'cancel'
    end
  end

  resources :comments do
    member do
      patch 'create'
      delete 'delete'
      patch 'update'
    end
  end

  resources :rsvps do
    member do
      patch 'update'
      get   'edit'
      patch 'update_email_comments_setting'
      get   'rsvp_reminder'
      get   'turn_off_comments'
      patch 'hide'
      patch 'unhide'
    end
  end

  namespace :admin do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  #Uploaders
  mount_uploader :event_photo, EventPhotoUploader

  #Callbacks
  before_save :save_url_photo

  #Relationships
  belongs_to :owner, :class_name => "User"
  has_many   :coming_rsvps, -> {where(response: Rsvp::YES)}, class_name: 'Rsvp',
                after_add: :update_is_tipped,
                before_remove: :update_is_tipped
  has_many   :rsvps
  has_many   :invitees, through: :rsvps, :source => :user

  #Accessors
  attr_accessor :owner_email
  attr_accessor :invitee_emails

  #Validations
  validates :hash_key, uniqueness: true
  validates_presence_of :name
  validate :maximum_is_not_less_than_sipping_point
  #These validations will prevent event statuses from being updated
  #validate :event_time_not_in_past
  #validate :rsvp_deadline_not_in_past
  validate :rsvp_deadline_is_before_event

  #Constants
  INITIALIZED = 'initalized'
  OPEN = 'open'
  EXPIRED = 'expired'
  CONFIRMED = 'confirmed'
  DELETED = 'deleted'

  #Scopes
  scope :open, -> { where(status:Event::OPEN) }
  scope :confirmed, -> { where(status:Event::CONFIRMED) }
  scope :deadline_passed, -> { where("deadline < ?", DateTime.now) }
  scope :upcoming, -> { where("time >= ?", Time.now - 2*3600) }
  scope :ready_for_report, -> { where("time <= ? and report_sent = false and status = ?", Time.now - 6*3600, Event::CONFIRMED)}
  scope :happening_within_24hrs, -> { where("time >= ? and time < ?", Time.now, Time.now + 24*3600)}
  scope :deadline_not_passed, -> { where("deadline >= ?", Time.now) }
  scope :not_expired, -> { where("status <> ?", Event::EXPIRED) }
  scope :tipped, -> { where(is_tipped: true)}
  scope :not_canceled, -> { where("status <> ?", Event::DELETED) }

  #Commentable
  acts_as_commentable

  #Methods
  def to_param
    self.hash_key
  end 

  def has_max_attendance?
    maximum_attendance.present?
  end

  def has_spots_remaining?
    unless has_max_attendance?
      return true
    else
      return (maximum_attendance > rsvps.said_yes.count)
    end
  end

  def is_full_up?
    !has_spots_remaining?
  end

  def tipped? 
    if threshold
      return coming_rsvps.count >= threshold
    else
      return false
    end
  end

  def is_over_threshold?
    if threshold 
      return coming_rsvps.count > threshold
    else
      return false
    end   
  end

  def percent_complete
    ([self.rsvps.said_yes.count.to_f/self.threshold,1].min)*100
  end    

  def rsvps_needed
    [(self.threshold - self.rsvps.said_yes.count), 0].max
  end

  def generate_hash_key
    if self.hash_key
      return self.hash_key
    else
      hash_key = Digest::MD5.hexdigest(self.name + self.owner.email + DateTime.now.to_s + rand.to_s)
      self.hash_key = hash_key
      self.save
      return hash_key 
    end
  end

  def update_status send_email=false
    #Once an event expires, it cannot un-expire
    if self.status == Event::EXPIRED
      return self.status

    #Once an event is canceled/deleted, it cannot be un-canceled/deleted
    elsif self.status == Event::DELETED 
      return self.status  
  
    # if the deadline passed and we haven't reached the SP, finalize the event# 
    elsif deadline < DateTime.now and self.rsvps.said_yes.count < self.threshold 
      if self.status != Event::EXPIRED and send_email
        send_expiration_emails
      end
      self.status = Event::EXPIRED
    
    else 
      # otherwise, set up the status appropriately
      if self.rsvps.count == 0 # The event has been created
        self.status = Event::INITIALIZED
      elsif tipped?  # The event is on!
        send_confirmation_emails if (self.status != Event::CONFIRMED and send_email)
        self.status = Event::CONFIRMED
      else # The event is awaiting RSVPs
        self.status = Event::OPEN
      end
    end

    self.save

    return self.status 
  end

  def new_comments
    self.comment_threads.where("created_at > ?", self.comments_last_mailed || self.created_at).order('created_at')
  end

  def invitee_emails_are_valid emails
    
    if emails.blank?
      return true
    end 
    emails = emails.split(/[,\n]/)
    emails.each do |email|
      unless email.blank?
        unless valid_email(email.strip.downcase)
          errors.add(:invitee_emails, email + " is not a valid email.")
          return false
        end
      end
    end

    return true

  end

  def has_passed?
    return self.time < Time.now
  end 

  def deadline_passed?
    return self.deadline < Time.now
  end

  def expired?
    return self.status == Event::EXPIRED
  end

  def deleted?
    return self.status == Event::DELETED
  end

  ####### Custom Getters/Setters #####
  def invitee_emails
    nil
  end

  def invitee_emails=(value)

    create_owner_rsvp

    emails = value.split(/[\n,]/).map(&:strip).reject(&:blank?)
    create_rsvps emails
    
  end

  def create_rsvps emails
    emails.each do |email|
      unless email.blank?
        user = User.find_or_create_by(email: email.strip.downcase) do |u|
          u.password = u.password_confirmation = Devise.friendly_token.first(8)
        end

        #delete the unfriendship
        unfriendships = Unfriendship.where(user: self.owner, unfriend: user)
        unfriendships.destroy_all

        rsvp = Rsvp.where(user: user, event: self).first_or_create
        rsvp.emailed = false
        rsvp.new_record?
        rsvp.generate_hash_key
        rsvp.save!
      end
    end 
  end

  def create_rsvps_from_ids ids
    ids.each do |id|
      user = User.find(id)
      unless id.blank?
        user = User.find(id)
        rsvp = Rsvp.where(user: user, event: self).first_or_create
        rsvp.emailed = false
        rsvp.new_record?
        rsvp.generate_hash_key
        rsvp.save!
      end
    end
  end

  def my_people_emails
    self.owner.my_people
  end

  #from auto_html gem how-to
  auto_html_for :description do
    html_escape
    image(:width => 50)
    youtube(:width => 700, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  def sipping_points
    SippingPoints::Event::TIPPED[tipped?] +
    coming_rsvps.count * SippingPoints::Event::ATTENDEE
  end

  ### End Custom Getters/Setters #####

  ########## String Generators #######

  def html_description #this method can be made obsolete by switching to auto_html
    if self.description_html
      return self.description_html
    elsif self.description
      return self.description.gsub("\n", "<br>")
    else 
      return ""
    end 
  end

  def email_description
    return self.html_description.gsub("<img src", "<img style='max-width: 600px;' src")
  end

  def display_time
    display self.time
  end

  def display_time_wordy
    display_wordy self.time
  end

  def display_deadline
    display self.deadline
  end

  def display_deadline_wordy
    display_wordy self.deadline
  end

  def display time
    #If time is not this year AND the month is more than 90 days away from now
    if(time.in_time_zone(timezone).year - Time.now.in_time_zone(timezone).year).abs > 0 and (time.in_time_zone(timezone) - Time.now.in_time_zone(timezone)).abs > 3*30*24*3600
      time.in_time_zone(timezone).strftime("%a, %b %-d, %Y %l:%M %p").gsub("  ", " ")
    else
     time.in_time_zone(timezone).strftime("%a, %b %-d, %l:%M %p").gsub("  ", " ")
    end
  end 

  def display_wordy time
    #If time is not this year AND the month is more than 90 days away from now
    if(time.in_time_zone(timezone).year - Time.now.in_time_zone(timezone).year).abs > 0 and (time.in_time_zone(timezone) - Time.now.in_time_zone(timezone)).abs > 3*30*24*3600
      time.in_time_zone(timezone).strftime("%A, %B %-d, %Y at %l:%M %p").gsub("  ", " ")
    else
     time.in_time_zone(timezone).strftime("%A, %B %-d at %l:%M %p").gsub("  ", " ")
    end
  end

  def yes_count_phrase
    yes_count = self.rsvps.said_yes.count
    if yes_count == 1
      return "1 person attending"
    else
      return yes_count.to_s + " people attending"
    end
  end  

  def past_yes_count_phrase
    yes_count = self.rsvps.said_yes.count
    if yes_count == 1
      return "1 person said Yes"
    else
      return yes_count.to_s + " people said Yes"
    end
  end



  def short_description
    case self.status
    when Event::OPEN
      return "Waiting for RSVPs" 
    when Event::INITIALIZED
      return "Invitations not Sent"
    when Event::EXPIRED
      return "Not Happening"
    when Event::DELETED
      return "Canceled"
    when Event::CONFIRMED
      return "It's On!"
    end
  end

  def wordy_html_status
    case self.status
    when Event::OPEN
      return "You have been invited, but this event won't happen unless we can get at least <strong>" + self.threshold.to_s + " " + "person".pluralize(self.threshold) + "</strong> to commit before the deadline."
    when Event::INITIALIZED
      return "How did you get here?  Invitations haven't been sent yet."
    when Event::EXPIRED
      return "This event failed to reach the Sipping Point.  Don't bother showing up because no one else is going to be there."
    when Event::DELETED
      return "This event was canceled by " + self.owner.display_name.strip + '.' 
    when Event::CONFIRMED
      return "This event is officially happening!"
    end
  end

  ####### End String Generators ###

  ########### Emails ##############

  def create_owner_rsvp
    Rsvp.where(user: self.owner, event: self).first_or_create do |rsvp|
      rsvp.generate_hash_key
      rsvp.response = Rsvp::YES
      rsvp.save!
    end
  end

  def send_confirmation_emails
    sendable_rsvps = self.rsvps.said_yes + self.rsvps.unanswered
    sendable_rsvps.each do |rsvp|
      UserMailer.confirmation_email(rsvp).deliver!
    end
  end   

  def send_expiration_emails
    sendable_rsvps = self.rsvps.said_yes + self.rsvps.unanswered
    sendable_rsvps.each do |rsvp|
      UserMailer.expiration_email(rsvp).deliver!
    end
  end 

  def send_rsvp_emails(invitor=nil)
    self.rsvps.each do |rsvp|
      unless rsvp.emailed?

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :authorized?

  # GET /events
  # GET /events.json

  def index
    @events = Event.all.order("id DESC")
    @monthly_array = Statistics.new.monthly_array
  end

  def authorized?
    unless current_user.administrator?
      redirect_to root_url
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::SanitizeHelper

  before_action :set_event, only: [:show, :edit, :update, :report, :update_report, :cancel]
  before_action :authenticate_user!, :except => [:show, :index, :update, :cancel]  
  after_action  :update_status, only: [:create, :show, :update]

  # GET /events
  # GET /events.json

  def index
    logger.info("Index Event")
    @events = Event.where(owner: current_user)
    @event = Event.new
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @comments = @event.comment_threads.order('created_at')
    @excuses = @event.rsvps.said_no.left_excuse

    set_comment_as

    @new_comment = Comment.new()

  end 

  def edit
    set_comment_as
    confirm_invitee
  end

  def new
    @event = Event.new
  
  end

  # POST /events.json
  def create

    logger.info('Create Event')

    params = update_time_params(event_params)
    @event = Event.new(params)

    @event.owner = current_user
    @event.generate_hash_key
    @event.update_status

    respond_to do |format|
      if @event.save
        format.html { redirect_to edit_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  def update

    @event.errors.clear   
    confirm_invitee

    #Pull out the allowed event_params
    event_params = event_params() 

    #Update Timezone
    event_params = update_time_params(event_params)

    old_friends = params.select { |key, value| key.to_s.match(/^!!!email\d+/) }
    old_friends = old_friends.values

    respond_to do |format|
      if @event.invitee_emails_are_valid params[:event][:invitee_emails] and @event.update(event_params)
        @event.description = params[:event][:description]
        @event.create_rsvps_from_ids old_friends
        if params['maximum_attendance'].to_i == -1
          @event.maximum_attendance = nil
        else
          @event.maximum_attendance = params['maximum_attendance'].to_i
        end
        @event.save
        @event.send_rsvp_emails(current_user) 
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def cancel
    confirm_owner
    unless @event.status == Event::DELETED
      @event.send_cancellation_emails
    end
    @event.status = Event::DELETED
    @event.save
    render json: {result: true}
  end

  def report
    confirm_owner
    
    unless @event.status == Event::CONFIRMED and @event.has_passed?
      redirect_to root_url
    end 
    
    @rsvps = @event.rsvps.said_yes.where("user_id <> ?", @event.owner.id)
  end

  def update_report

    confirm_owner
    @rsvps = @event.rsvps.said_yes
    @rsvps.each do |rsvp|
      unless params[rsvp.user.email].nil?
        # the contents of params[rsvp.user.email] will be based on flake report
        #   Showed Up   =>  1
        #   Flaked      =>  0
        #   No Response => -1
        # NB: No Response attendance reports will be stripped
        if params[rsvp.user.email].to_i == Rsvp::NO_RESPONSE
          rsvp.attendance_report = nil
        else
          rsvp.attendance_report = params[rsvp.user.email].to_i
        end
        rsvp.save
      end
    end 

    respond_to do |format|
      format.html { redirect_to @event, notice: 'Thanks for submitting your Flake Report.' }
      format.json { render :show, status: :ok, location: @event }
    end

  end

  def caltest
    respond_to do |format|
      format.html {render :caltest, :layout => false}
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by(hash_key: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :owner_email, :threshold, :maximum_attendance, :name, :time, :description, :deadline, :invitee_emails, :location, :open, :timezone, :cover_photo_url)
    end

    #Set Comment As
    def set_comment_as
      @rsvp_hash_key = params[:rsvp]
      @rsvp = Rsvp.find_by(hash_key: @rsvp_hash_key)
      if @rsvp
        @rsvp.viewed = true
        @rsvp.save 
      end

      if current_user
        @comment_as = current_user
        @rsvp = Rsvp.find_by(event: @event, user: current_user)
        if @rsvp
          @rsvp.viewed = true
          @rsvp.save
        end
      elsif @rsvp_hash_key
        @comment_as = @rsvp.user
      else
        @comment_as = nil
      end

    end

    def confirm_owner
      unless @event.owner == current_user 
        redirect_to root_url
      end     
    end 

    def confirm_invitee
      unless current_user == @event.owner or (current_user and @event.open and current_user.is_invited_to? @event)
        redirect_to root_url
      end
    end

    def send_rsvp_emails
      @event.send_rsvp_emails
    end

    def update_status
      @event.update_status(true)
    end 

    def confirm_editing_rights

    end

    def update_time_params params
      #The input from the new even form retuns the time and time zone as two separate fields
      #This functions creates the time with the correct time zone and then throws away the timeezone field

      unless params['time'].nil?
        Time.zone = params['timezone']
        new_time = Time.zone.parse(params['time']) 
        new_deadline = Time.zone.parse(params['deadline'])
        params['time'] = new_time
        params['deadline'] =  new_deadline
      end

      return params
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_excuses.html.haml
-if current_user == @event.owner and @excuses.count > 0

  %h2  
    Excuses
  Only the event organizer sees excuses.  

  -@excuses.each do |rsvp|
    -unless rsvp.excuse.blank?
      .panel.translucent
        .panel-body 
          %div
            .col-md-12
              .message-header-text
                =rsvp.user.display_name
          %div
            .col-md-12
              .message-body-text
                =rsvp.excuse.html_safe




  

app/views/events/index.html.haml
%br
%button.btn.btn-primary.btn-lg.center-block{"data-target" => "#myModal", "data-toggle" => "modal"}
  Let's Drink!

-@events.each do |event|
  =link_to event.name, event_path(event)
  = "<>"   

= render "new_event_modal"

app/views/events/new.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>New Event</h1>
            <%= render 'form' %>
        </div>
    </div>
</header>

app/views/events/show.html.haml
%section.static-header
  %div.container
    %h1.static-header-title
      =@event.name
    %h3
      -if current_user == @event.owner and @event.rsvps.count == 0
        %a.btn.btn-primary.btn-sm{:href => edit_event_path(@event)} Let's invite some people!
      - if current_user == @event.owner and @event.rsvps.count > 0
        %a.btn.btn-primary.btn-sm{:href => edit_event_path(@event)} Edit Details   
    
    .panel.translucent
      .panel-body
        .panel-text
          %h3
            -if @event.event_photo.url
              .div.event-cover
                %img{src: @event.event_photo.url}
            -if @event.status == Event::INITIALIZED
              ="This event has been created, but no one has been invited yet."
            -elsif @event.status == Event::OPEN
              ="This event is awaiting RSVPs"
            -elsif @event.status == Event::CONFIRMED
              ="This event has reached The Sipping Point!  It's officially happening!"
            -elsif @event.status == Event::EXPIRED
              ="This event failed to reach The Sipping Point.  It is canceled."
            -elsif @event.status == Event::DELETED
              ="This event has been CANCELED by " + @event.owner.display_name.to_s + '.'
          -if @event.is_full_up?
            %h4
              %strong
                ="This event has reached maximum capacity."
          %hr
          %h4
            -unless @event.description.blank?
              %div.event-description
                =@event.description_html || @event.html_description.html_safe
          %h5
            ="Organized by #{@event.owner.display_name}"

    %div.col-md-6
      %h2
        Event Details
      .panel.translucent
        .panel-body
          .panel-text
            %table.table.table-center
              %tr
                %td
                  Sipping Point
                %td
                  =@event.threshold.to_s + ' people'
              -if @event.maximum_attendance
                %tr
                  %td
                    Maximum
                  %td
                    =@event.maximum_attendance.to_s + ' people'
              %tr
                %td
                  Location
                %td
                  =@event.location
              %tr
                %td
                  Date & Time
                %td
                  =@event.display_time
              %tr
                %td
                  Deadline to Respond
                %td
                  -unless @event.deadline.nil?
                    =@event.display_deadline
          
          
          = link_to  "http://www.google.com/calendar/event?action=TEMPLATE&text=" + CGI.escape(@event.name || "") + "&dates=" + @event.time.strftime("%Y%m%dT%H%M%S") +"/" + (@event.time + 7200).strftime("%Y%m%dT%H%M%S") + "&details=" + CGI.escape(@event.description.to_s || "") + "&location=" + CGI.escape(@event.location || ""), :target => "blank" do  
            %i.fa.fa-calendar.fa-stack-2x.panel-text
            %br
            %br
            ="Add to GCal"



      -if @event.rsvps.count > 0
        %h2
          Who's Coming?
        .panel.translucent
          .panel-body
            .panel-text
              .col-md-6
                %table.table.table-center
                  %tr
                    %td
                      Going
                    %td
                      =@event.rsvps.said_yes.count
                  %tr
                    %td
                      Not Going
                    %td
                      =@event.rsvps.said_no.count
                  %tr
                    %td
                      Unanswered
                    %td
                      =@event.rsvps.unanswered.count
              .col-md-6
                -unless @event.status == Event::DELETED
                  .very-large-font
                    =@event.rsvps_needed
                  more needed to party
                -else
                  .very-large-font
                    %i.fa.fa-ban
                .progress
                  -if @event.status == Event::CONFIRMED
                    .progress-bar.progress-bar-info{:role => "progressbar", :style => "width:" + @event.percent_complete.to_s + "%"}
                      =@event.percent_complete.round.to_s + "%"
                  -elsif @event.status == Event::EXPIRED 
                    .progress-bar.progress-bar-danger{:role => "progressbar", :style => "width:" + @event.percent_complete.to_s + "%"}
                      =@event.percent_complete.round.to_s + "%"
                  -elsif @event.status == Event::DELETED
                    ="CANCELED"
                  -else 
                    .progress-bar.progress-bar-danger.progress-bar-striped.active{:role => "progressbar", :style => "width:" + @event.percent_complete.to_s + "%"}
                      =@event.percent_complete.round.to_s + "%"
                  
              %table.table.table-center.table-striped.put-in-middle{id: 'whos-coming', :style => "display: table; vertical-align: middle;"}
                %thead
                  %tr
                    %th.text-center
                      Invitee
                    %th.text-center
                      Reliability
                    %th.text-center
                      Going?
                %tbody.put-in-middle      
                  - @event.rsvps.each do |rsvp|
                    -unless rsvp.user.nil?
                      %tr.put-in-middle{style: "vertical-align: middle;"}
                        %td.put-in-middle
                          -unless rsvp.user.avatar_url.blank?
                            %img.img-circle{src: rsvp.user.avatar_url, style: "height: 60px; width: 60px;"}
                            %br
                          -if current_user == rsvp.user
                            = link_to (truncate(rsvp.user.display_name, length: 35) || "") + " (Me)", user_path(rsvp.user)
                          -else
                            = link_to truncate(rsvp.user.display_name, length: 35), user_path(rsvp.user)
                        %td.put-in-middle
                          -reliability_factor = rsvp.user.reliability_factor
                          -if reliability_factor
                            =(reliability_factor * 100).round.to_s + "%"
                        %td.put-in-middle
                          -if current_user == rsvp.user or @comment_as == rsvp.user
                            -if rsvp.response == 1
                              = link_to 'Yes', edit_rsvp_url(rsvp)
                            -elsif rsvp.response == 0
                              = link_to 'No', edit_rsvp_url(rsvp)
                            -else
                              = link_to 'Click to Respond', edit_rsvp_url(rsvp)
                          -else
                            -if rsvp.response == 1
                              ="Yes"
                            -elsif rsvp.response == 0
                              ="No"
                            -else
                              -if current_user == @event.owner  
                                %div{:style => "font-size: 10px;"}
                                  =rsvp.viewed ? "RSVP seen" : "RSVP not seen"
                              -if current_user == @event.owner and not @event.deadline_passed? and not @event.deleted?
                                %div
                                  %button.btn.btn-xs.reminder_button{"data-id" => rsvp.hash_key }
                                    Send Reminder
                              -if current_user == @event.owner  
                                %div{:id => (rsvp.hash_key + '_message'), :style => "font-size: 10px;"}
                                  =rsvp.reminded_time_string
                              -else
                                =""
              %table.table.table-center.table-striped{id: 'whos-coming-m', :style => "display: table;"}
                %thead
                  %tr
                    %th.text-center
                      Invitees
                %tbody      
                  - @event.rsvps.joins(:user).order('rsvps.response DESC NULLS LAST, users.name ASC, users.email ASC').each do |rsvp|
                    -unless rsvp.user.nil?
                      %tr
                        %td                          
                          %div.col-md-12
                            -unless rsvp.user.avatar_url.blank?
                              %img.img-circle{src: rsvp.user.avatar_url, style: "height: 60px; width: 60px;"}
                              %br
                            -if current_user == rsvp.user
                              = link_to (truncate(rsvp.user.display_name, length: 35) || "") + " (Me)", user_path(rsvp.user)
                            -else
                              = link_to truncate(rsvp.user.display_name, length: 35), user_path(rsvp.user)
                          %div.col-md-12
                            -reliability_factor = rsvp.user.reliability_factor
                            -if reliability_factor
                              =(reliability_factor * 100).round.to_s + "%" + " reliability"
                          %div.col-md-12
                            -if current_user == rsvp.user or @comment_as == rsvp.user
                              -if rsvp.response == 1
                                = link_to 'Going', edit_rsvp_url(rsvp)
                              -elsif rsvp.response == 0
                                = link_to 'Not Going', edit_rsvp_url(rsvp)
                              -else
                                = link_to 'Click to Respond', edit_rsvp_url(rsvp)
                            -else
                              -if rsvp.response == 1
                                ="Going"
                              -elsif rsvp.response == 0
                                ="Not Going"
                              -else
                                -if current_user == @event.owner  
                                  %div{:style => "font-size: 10px;"}
                                    =rsvp.viewed ? "RSVP seen" : "RSVP not seen"
                                -if current_user == @event.owner and not @event.deadline_passed? and not @event.deleted?
                                  %div
                                    %button.btn.btn-xs.reminder_button{"data-id" => rsvp.hash_key }
                                      Send Reminder
                                -if current_user == @event.owner  
                                  %div{:id => (rsvp.hash_key + '_m_message'), :style => "font-size: 10px;"}
                                    =rsvp.reminded_time_string
                                -else
                                  =""

      -if current_user == @event.owner and @event.rsvps.count == 0
        %a.btn.btn-primary.btn-xl{:href => edit_event_path(@event)} Let's invite some people!
      - if current_user == @event.owner and @event.rsvps.count > 0
        %a.btn.btn-primary.btn-xl{:href => edit_event_path(@event)} Edit Details  
      - elsif current_user and current_user.is_invited_to? @event and @event.open
        %a.btn.btn-primary.btn-xl{:href => edit_event_path(@event)} Invite More People!
      - elsif @event.open and @comment_as and @comment_as.is_invited_to? @event
        ="Hey " + @comment_as.display_name + ","
        %a{:href => new_user_session_path} Sign In
        or 
        %a{:href => new_user_registration_path} Sign Up 
        to invite more people to this event.


    %div.col-md-6
      = render :partial => "comments"
      = render :partial => "excuses"


:javascript
  //Set tables if screen gets too small
  function respond(){
    if ((window.innerWidth>=568 && window.innerWidth<970) || (window.innerWidth>=1200)) {
      $('#whos-coming').show();
      $('#whos-coming-m').hide();
    }
    else  {
      $('#whos-coming').hide();
      $('#whos-coming-m').show();
    }
  };

  // Reminder Button 
  $(".reminder_button").click(function(){
       // Get the id data attribute
       var id = $(this).data("id");
       $.ajax({
        type: 'GET',
        url: '#{root_url}' + 'rsvps/' + id + '/rsvp_reminder'
       })
       .done(function(data) {
        console.log(data);
        document.getElementById(id + '_message').innerHTML = data['message'];
        document.getElementById(id + '_m_message').innerHTML = data['message'];
       });
  });

  $(document).ready(function() {
    $('#whos-coming').dataTable({
      "bPaginate": false, "bFilter": false, "bInfo" : false,
      "order": [[ 2, "desc" ],[0, "asc"]]
    });

    respond();

  } );

  window.onresize = function() {
    respond();
  };




       



                