config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post "/google_login" => "users/sessions#google_create"
  end
  
  resources :users do
    member do
      get 'events'
      get 'hidden_events'
    end
    resources :unfriendships
  end 
  
  resources :events 

  resources :events do 
    member do
      get 'caltest'
      get 'report'
      patch 'report', action: 'update_report'
      post 'cancel'
    end
  end

  resources :comments do
    member do
      patch 'create'
      delete 'delete'
      patch 'update'
    end
  end

  resources :rsvps do
    member do
      patch 'update'
      get   'edit'
      patch 'update_email_comments_setting'
      get   'rsvp_reminder'
      get   'turn_off_comments'
      patch 'hide'
      patch 'unhide'
    end
  end

  namespace :admin do
    resources :events
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Used for Google Sign in -->
    <meta name="google-signin-client_id" content=<%= Rails.application.config.google_api_client_id %> >

    <title>The Sipping Point</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/assets/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/assets/font-awesome.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="/assets/animate.min.css" type="text/css">


    <!-- Custom CSS -->
    <link rel="stylesheet" href="/assets/creative.css" type="text/css">
    <link rel="stylesheet" href="/assets/jquery.dataTables.css" type="text/css">

    <!-- Finds the correct favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/assets/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/assets/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/assets/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/assets/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png">
    <link rel="manifest" href="/assets/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/assets/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>

.navbar-shrink {
        background-color: #FFF !important;
        border-color: #222;
}

.logo-shrink {
  color: #222 !important;
  opacity: 0.7;
}

.logo-shrink:hover {
  opacity: 1;
}


</style>
</head>

<body id="page-top">

  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand page-scroll my-scroll" href="/">The Sipping Point</a>

          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <% if user_signed_in? %>
                    <% if current_user.administrator? %>
                      <li>
                        <%= link_to 'Admin', admin_events_path, :class => 'page-scroll my-scroll' %>
                      </li>
                    <% end %> 
                    <li>
                      <%= link_to 'New Event', new_event_path, :class => 'page-scroll my-scroll' %>
                    </li>


                    <li>
                      <%= link_to events_user_path(current_user), :class => 'page-scroll my-scroll' do %>
                        My Events <% if current_user.rsvps.not_expired.upcoming.not_canceled.where(response: nil).count > 0
 %><span class="badge"><%= current_user.rsvps.not_expired.upcoming.not_canceled.where(response: nil).count %>
</span><% end %>
                      <% end %>

                    </li> 
                    <li>
                       <%= link_to 'Profile', user_path(current_user), :class => 'page-scroll my-scroll' %>
                    </li>                     
                    <li>
                       <%= link_to 'Account', edit_user_registration_path, :class => 'page-scroll my-scroll' %>
                    </li>
                    <li>
                       <%= link_to "Logout", '#', :class => 'page-scroll my-scroll', :id => 'logout_link'  %>
                    </li>
                  <% else %>
                    <li>
                        <%= link_to "Sign up", new_user_registration_path, :class => 'page-scroll my-scroll'  %> 
                    </li>
                    <li>
                        <%= link_to "Login", new_user_session_path, :class => 'page-scroll my-scroll'  %>
                    </li>
                  <% end %>  
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>

<%= yield %>


<!-- Google API: Used for Sign In -->
<script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
<!-- Bootstrap Core JavaScript -->
<script src="/assets/bootstrap.min.js"></script>
<scirpt src="assets/jquery.dataTables.min.js"></script>
<scirpt src="assets/d3.min.js"></script>
<!-- Javascript for finding the browser time zone -->
<scirpt src="assets/jstz.min.js"></script>


<script>
  $(function(){
    $(window).scroll(function(){
        if ($(this).scrollTop() > 100){
            $('.navbar-default').addClass('navbar-shrink');
            $('.my-scroll').addClass('logo-shrink');
        }
        else{
            $('.navbar-default').removeClass('navbar-shrink');
            $('.my-scroll').removeClass('logo-shrink');
        }
    });
  });

  $('#logout_link').click( 
    function(e) {
      e.preventDefault(); 
      signOutGoogle();
    });

  function signOutGoogle() {
    var auth2 = gapi.auth2;
    //var auth2 = gapi.auth2.getAuthInstance();
    if(auth2 == null){
      console.log('the thing is null');
      //signOutSippingPoint();
    }
    else{
      console.log('the thing is NOT null');
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.signOut().then(function () {
        console.log('Google User signed out.');
        signOutSippingPoint();
      });
    }
  }

  function signOutSippingPoint() {

    //console.log(<%= root_url %> + '/users/sign_out');
    //console.log(<%= root_url %>  + 'users/' + '1' + '/unfriendships');
    $.ajax({
      url: '<%= root_url %>' + 'users/sign_out',
      type: 'DELETE',
      success: function(result) {
        location.href = '<%= root_url %>' // Do something with the result
        return 
      }
    });
    return
    location.href =  '#{root_url}' + 'users/sign_out'
  }

  function loadIT() {
    console.log ('fucking loading it')
    gapi.load('auth2', function() {
      gapi.auth2.init();
    });
  }

  $(window).load(function() {
    loadIT();
  });

</script>
</body>
</html>